apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 200Mi
        env:
        - name: CONFIG_PATH
          value: /etc/cdk8s/config.json
        volumeMounts:
        - mountPath: /etc/cdk8s
          name: cdk8s-config
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cdk8s-config
          configMap:
            name: cdk8s-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cdk8s-config
  namespace: system
  labels:
    control-plane: controller-manager
data:
  config.json: |
    {}
