# permissions for end users to view applicationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationtemplate-viewer-role
rules:
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - applicationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - applicationtemplates/status
  verbs:
  - get
