# permissions for end users to edit applicationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationtemplate-editor-role
rules:
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - applicationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - applicationtemplates/status
  verbs:
  - get
