# permissions for end users to edit apppipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apppipeline-editor-role
rules:
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - apppipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - apppipelines/status
  verbs:
  - get
