# permissions for end users to view apppipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apppipeline-viewer-role
rules:
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - apppipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - modoki.tsuzu.dev
  resources:
  - apppipelines/status
  verbs:
  - get
