name: Docker
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  operator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: modokipaas/modoki-operator
        dockerfile: Dockerfile
        tag_with_ref: true
        tag_with_sha: true
