name: Docker
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  operator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: modokipaas/modoki-operator
        dockerfile: Dockerfile
        tag_with_ref: true
        tag_with_sha: true

    - name: Extract ref
      id: ref
      uses: actions/github-script@v3.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/(tags|heads)\//, '');

    - name: Set up kind(Kubernetes 1.18.2)
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
        config: ./.github/kind.yaml

    - name: Set up modoki-paas/kubernetes-openapi-generated
      uses: actions/checkout@v2
      with:
        repository: 'modoki-paas/kubernetes-openapi-generated'
        path: kubernetes-openapi-generated
        clean: "false"

    - run: |
        kustomize build ${GITHUB_WORKSPACE}/config/crd | kubectl apply -f -
        kubectl proxy &
        sleep 5
        curl localhost:8001/openapi/v2 | grep modoki
        cd kubernetes-openapi-generated
        git switch ${{ steps.ref.outputs.result }} || git switch --no-guess -c ${{ steps.ref.outputs.result }}
        git branch