name: Docker
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  operator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get token
      id: get_token
      uses: machine-learning-apps/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}
    - name: Get App Installation Token
      run: |
        echo "This token is masked: ${TOKEN}"
      env: 
        TOKEN: ${{ steps.get_token.outputs.app_token }}

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: modokipaas/modoki-operator
        dockerfile: Dockerfile
        tag_with_ref: true
        tag_with_sha: true

    - name: Extract ref
      id: ref
      uses: actions/github-script@v3.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/refs\/(tags|heads)\//, '');

    - name: Set up kind(Kubernetes 1.18.2)
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
        config: ./.github/kind.yaml

    - name: Set up modoki-paas/kubernetes-openapi-generated
      uses: actions/checkout@v2
      with:
        repository: 'modoki-paas/kubernetes-openapi-generated'
        path: kubernetes-openapi-generated
        clean: "false"

    - name: Generate swagger.json
      run: |
        kustomize build ${GITHUB_WORKSPACE}/config/crd | kubectl apply -f -
        kubectl proxy &
        sleep 5
        curl localhost:8001/openapi/v2 > ./swagger.json
        cd kubernetes-openapi-generated
        export BRANCH=${{ steps.ref.outputs.result }}
        git switch $BRANCH || git switch --no-guess -c $BRANCH
        mkdir -p api/openapi-spec
        cp ../swagger.json api/openapi-spec/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m 'Update swagger.json for ${{ steps.ref.outputs.result }}'

    - name: Push to kubernetes-openapi-generated
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ steps.get_token.outputs.app_token }}
        directory: ./kubernetes-openapi-generated
        branch: ${{ steps.ref.outputs.result }}
        repository: modoki-paas/kubernetes-openapi-generated
