name: Webhook
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: modokipaas/webhook
        dockerfile: webhook/Dockerfile
        tag_with_ref: true
        tag_with_sha: true
        push: ${{ github.event_name == 'push' }}
